linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused